approvedGitRepositories: []

compressionLevel: mixed

enableGlobalCache: true

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - "@webiny/*"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
