approvedGitRepositories: []

compressionLevel: mixed

enableGlobalCache: true

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 2d

npmPreapprovedPackages:
  - "@webiny/di"
  - "@webiny/stdlib"

yarnPath: .yarn/releases/yarn-4.15.0.cjs
